name: Auto Tag, Build and Push Containerfile

on:
  workflow_dispatch:  # Executado manualmente

jobs:
  tag-build-push:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Gerar nova tag (formato: vYYYYMMDD-HHMM)
        id: tag
        run: |
          TAG="v$(date -u +'%Y%m%d-%H%M')"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "::set-output name=tag::$TAG"

      - name: Criar tag no repositório
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ env.TAG }}
          git push origin ${{ env.TAG }}

      - name: Logar no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build da imagem usando Containerfile
        run: |
          docker build -f Containerfile -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} .

      - name: Push da imagem
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
