name: Build and Push Docker Image with Git Tag

on:
  push:
    tags:
      - 'v*'  # Só executa em pushes de tags começando com "v"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Logar no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build da imagem Docker
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          TAG=${GITHUB_REF#refs/tags/}
          docker build -t $IMAGE_NAME:$TAG .

      - name: Push da imagem Docker
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          TAG=${GITHUB_REF#refs/tags/}
          docker push $IMAGE_NAME:$TAG
